* Makefile.am, configure.ac: use misc/update-latest-release.rb to   update the latest release automatically.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -58,6 +58,38 @@ update-po:
 	  sort > po/POTFILES.in
 	cd po && $(MAKE) $(AM_MAKEFLAGS) update-po
 
+update-latest-release:
+	@if test -z "$(OLD_RELEASE)"; then	\
+	  echo "\$$(OLD_RELEASE) is missing";	\
+	  exit 1;				\
+	fi
+	@if test -z "$(OLD_RELEASE_DATE)"; then		\
+	  echo "\$$(OLD_RELEASE_DATE) is missing";	\
+	  exit 1;					\
+	fi
+	@if test -z "$(NEW_RELEASE_DATE)"; then		\
+	  echo "\$$(NEW_RELEASE_DATE) is missing";	\
+	  exit 1;					\
+	fi
+	cd $(top_srcdir) &&					\
+	  misc/update-latest-release.rb				\
+	  $(OLD_RELEASE) $(OLD_RELEASE_DATE)			\
+	  $(VERSION) $(NEW_RELEASE_DATE)			\
+	  milter-manager.spec.in				\
+	  html/index.html					\
+	  html/index.html.ja					\
+	  html/blog/tdiary.conf					\
+	  doc/reference/header$(RELEASE_TYPE_SUFFIX).html	\
+	  doc/reference/header$(RELEASE_TYPE_SUFFIX)-ja.html	\
+	  doc/install-to-centos.rd				\
+	  doc/install-to-centos.rd.ja				\
+	  doc/install-to-freebsd.rd				\
+	  doc/install-to-freebsd.rd.ja				\
+	  doc/upgrade-on-centos.rd				\
+	  doc/upgrade-on-centos.rd.ja				\
+	  doc/upgrade-on-freebsd.rd				\
+	  doc/upgrade-on-freebsd.rd.ja
+
 tag:
 	svn ls $(SF_REPOS)/tags/$(VERSION) > /dev/null 2>&1; 	\
 	  if test "$$?" = "0"; then				\
